### ISSUE TITLE
Develop Response Action RA2117: Analyse user-agent

### ISSUE THREAD

**Issue by yugoslavskiy** [atc-project/atc-react#306]
We are seeking for help with Response Actions development. You are very welcome to contribute. Please use the existing placeholder for the [RA2117: Analyse user-agent](https://github.com/atc-project/atc-react/tree/master/response_actions/RA_2117_analyse_user-agent.yml), as well as the [Response Action template](https://github.com/atc-project/atc-react/blob/master/response_actions/respose_action.yml.template) and our [contrib guide](https://github.com/atc-project/atc-react/blob/master/CONTRIBUTING.md).

**Comment by pjabes** [comment]
Hi Team, 

To avoid the duplication of work during [OSCD Sprint 2](https://oscd.community/sprints/sprint_2.html), I've picked this ticket up and am actively working on it.  Should have something out shortly.

**Comment by pjabes** [comment]
> Should have something out shortly.
A few months later I have actually been able to pick this up.

This is not complete yet but, @yugoslavskiy and others, could you please provide feedback on the writing-style/content of the [following](https://github.com/pjabes/atc-react/blob/issue-306/response_actions/RA_2117_analyse_user-agent.yml)?  I would just like to do a pulse check that what I am producing is in-line with the project.  I have tried to leverage the sample Response Actions and Contrib guide as much as possible.

Thanks,
Patrick

**Comment by pjabes** [comment]
Have created the PR for this - but as mentioned previously, I am more than happy to accept writing-style, formatting and content feedback as I hope to build out some additional response actions in the future.

**Comment by yugoslavskiy** [comment]
Hello @pjabes! Sorry for the late reply. 

I like the content you've developed, it is definitely valuable for the others.
I would only ask you to change the formatting to the [Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) (it won't take much time to adjust it).

I also added the link to Markdown Cheatsheet into both RA and RP templates, so it would be simpler to get in the right direction in the future (: 

Thank you very much! 
Looking forward to your adjustments! 
Will merge it right after that.
