### ISSUE TITLE
[Question] Response Action - Respond to User/Client

### ISSUE THREAD

**Issue by nicpenning** [atc-project/atc-react#319]
Any thoughts about a response action for responding to clients that reported an email to the security team?

When a user successfully reports a malicious email, I believe it is important to follow up with a message to let them know they successfully reported a malicious message to encourage further vigilance.

This could fall in:
RA1003 | Raise personnel awareness or 
RA1004 | Make personnel report suspicious activity

but I wasn't sure if this should be it's own action or not. Just throwing this out there.

Thanks!

**Comment by yugoslavskiy** [comment]
Hello @nicpenning ! 

Sorry for the delayed answer. We are now working on the second [OSCD sprint](https://oscd.community/) announcement, extremely busy schedule. 

It totally makes sense to add such action to one of the existing Response Actions or create a new one.
We will add it to the backlog and implement it in the next sprints. 

Thank you!

**Comment by nicpenning** [comment]
No problem! Thanks for the work you and others have put into this. I will try to contribute where I can. I look forward to the announcement.
