### ISSUE TITLE
 How to place RE&CT after the publication of MITRE shield framework

### ISSUE THREAD

**Issue by Karneades** [atc-project/atc-react#320]
See https://www.darkreading.com/attacks-breaches/mitre-releases-shield-active-defense-framework-/d/d-id/1338741 and https://shield.mitre.org/matrix/.

It's table and columns are different but maybe of some value for RE&CT or RE&CT is more detailed and more helpful for defenders and IR then the generic MITRE table.

**Comment by yugoslavskiy** [comment]
Hello @Karneades ! 

Sorry for the delayed answer. 
We are now working on the [second OSCD sprint](https://oscd.community/), which will start next Monday. 
Extremely busy schedule.

Thank you for your question. SHIELD looks nice, as any different point of view on a similar problem. 
It totally makes sense to enrich RE&CT with its tags, which will provide both projects with a better context. 
Would you like to contribute some of the mappings? 
Or maybe you have some plans regarding existing PRs you've created?

Thank you and have a great day!

**Comment by dtclayton** [comment]
@Karneades what do you see is the issue here? I am not sure there is so much overlap between the frameworks to really merit anything additional...

What are your thoughts?

**Comment by Karneades** [comment]
Trying to find mappings seems hard because namings are mostly different. Purpose of this issue was also to highlight the new framework.
