### ISSUE TITLE
Wrong path in generated documents and site on Windows

### ISSUE THREAD

**Issue by hatemp** [atc-project/atc-react#322]
On Windows 10, using Python 3.8.0, the paths to the response actions (from the playbook pages) are not correct. The generated paths contain the folder of the _response_actions_dir_ configured in _config.yml_. This is caused by the fact that on Windows, the default _os.path_ _join_ method uses the native Windows backslash as path seperator, whereas the remainder of the code expects the POSIX style forward slash. 

This can be fixed easily by changing line

`from os.path import isfile, join`

into

`from posixpath import isfile, join`

in file _scripts/reactutils.py_.

**Comment by yugoslavskiy** [comment]
Hello @hatemp ! 

Sorry for the delayed answer. 
We are now working on the [second OSCD sprint](https://oscd.community/), which will start next Monday. Extremely busy schedule. 

Thank you very much for your contribution. It is extremely beneficial for the community. 
Please don't hesitate to tell us more about issues with the project, or maybe interesting ideas of how to make it better.

Have a great day!
