### ISSUE TITLE
Make generated web site available without the need of a web server

### ISSUE THREAD

**Issue by hatemp** [atc-project/atc-react#323]
The __mkdocs_ build_ step, generates the web site based on the generated _mkdocs_ documentation. Currently a web server is needed to be able to use the generated web site since it is relying on selecting _index.html_ by default in case a directory is referenced. In cases when the information is also needed locally, not able to connect to the web server hosting these pages, the site should be generated such, that it also could be used without the need for a web server (accessing the web pages file directly from the browser). This allows the use of it without the overhead to install a web server locally.

This can easily be done by adding the _mkdocs_ option 

`use_directory_urls: false`

in the _script/templates/mkdocs_config_template.md.j2_ file

This could be added optionally (based on an option given to _main.py_) or permanently (since it does not prevent functioning correctly throng a web server when using this option).

**Comment by yugoslavskiy** [comment]
Hello @hatemp !

Technically, the scripts don't build the site using mkdocs, they only generate mkdocs navigation/config file.
We build it manually at the moment, as well as the users.
I've checked mkdocs build options, and found one that could help to work out the issue:

```
mkdocs build --help
[...]
  --use-directory-urls / --no-directory-urls
                                  Use directory URLs when building pages (the
                                  default).
[...]
```

It seems that you don't have to alter our template in `script/templates/mkdocs_config_template.md.j2`, you can just add this option while building the website with mkdocs.

Let me know if it works for you so I could close the issue.

Thank you again!

**Comment by hatemp** [comment]
Hi,

 

I missed that option on mkdocs; I tried it and it worked with the original template file. Issue can be closed; thanks for the reply.

 

Regards,

Harald
