### ISSUE TITLE
Support of sub-techniques

### ISSUE THREAD

**Issue by hatemp** [atc-project/atc-react#331]
When a sub-technique is specified in the tags section of the playbook YAML file, it is not recognized and treated as a technique.
Suggestion to handle these sub-techniques as a technique.

To allow for this, replace the $ in the (amitt) technique_re with `(\.\d{1,3})?$` in _responseplaybook.py_ and replace the "." in the identifier with a "/" in the playbook jinja template file.

**Comment by yugoslavskiy** [comment]
Hello @hatemp! First of all, thank you for your continuous support! 
My apologies for the delayed reply, we are still occupied with the OSCD stuff.
I've added sub-techniques support using your regex example. 

>  the (amitt) technique_re

double-checked if AMITT has sub-techniques. It seems not (yet?).

Will do a PR in a few minutes.
