### ISSUE TITLE
Rect enterprise matrix image doesn't show on mobile if clicked

### ISSUE THREAD

**Issue by arialies** [atc-project/atc-react#337]
When using the GitHub app, I tried to click on the RECT enterprise matrix image and instead of viewing the image I was given (what is believe) is the code used to generate the image.

**Comment by yugoslavskiy** [comment]
Hello @arialies! 

I believe that you saw the source code of the svg image. 
As long as you open it via your web browser on your mobile phone it rendered as it should:

https://raw.githubusercontent.com/atc-project/atc-react/master/docs/images/react_navigator_export_v5.svg

For some reason, the GitHub app opens it as a source code.
I am not sure if we can fix that, as it's the issue (or a feature?) of the GitHub app.

Thank you for the interest in the project and don't hesitate to provide any other feedback you have!
