### ISSUE TITLE
Upload to confluence using PAT

### ISSUE THREAD

**Issue by d3anp** [atc-project/atc-react#347]
It would be great to have confluence upload using a personal access token that is created at https://id.atlassian.com/manage-profile/security/api-tokens, as well as providing the token to main.py as a configuration item when using -C or --confluence.

This will give flexibility when using atc-react as part of a CICD pipeline.

**Comment by yugoslavskiy** [comment]
Hello @d3anp! Thank you for your proposal and interest in the project. It sounds great! (: Would you like to proceed with a PR?

**Comment by yugoslavskiy** [comment]
fixed by https://github.com/atc-project/atc-react/pull/348
