### ISSUE TITLE
Customisable Title formatting rules 

### ISSUE THREAD

**Issue by xofolowski** [atc-project/atc-react#354]
Currently, formatting rules for RA/RP titles are hardcoded.
Would be nice to have that customisable, as already discussed in Slack channel.
Will be issuing an appropriate PR shortly.

**Comment by yugoslavskiy** [comment]
Hello @xofolowski! Thank you for your contribution. 
Our CI/CD build failed with an [error](https://github.com/atc-project/atc-react/pull/356#issuecomment-903364049). Could you please fix it and re-create your PR? 
Thank you and have a great week!
