### ISSUE TITLE
Should we add confluence export to the project?

### ISSUE THREAD

**Issue by yugoslavskiy** [atc-project/atc-react#5]
Please provide your opinion on the topic.

**Comment by morallo** [comment]
I vote YES.
We are considering adopting RE&CT. Confluence is our current internal KB and would directly benefit from this.

**Comment by yugoslavskiy** [comment]
Hello @morallo ! 

This functionality is currently supported by the [main](https://github.com/atc-project/atomic-threat-coverage) project (we should have mentioned that). You can export RE&CT stuff into confluence from there. 
At the same time, I think it makes sense to do it separately. 

Would you like to have this function here, in the atc-react itself?

**Comment by morallo** [comment]
We are for now planning to adopt just RE&CT, not the full ATC project. I think it makes sense for our incident response team. Monitoring team has their own documentation and workflow, already mature and harder to migrate to ATC.

Is it possible to export selectively from the main project (I didn't research in depth)?

**Comment by yugoslavskiy** [comment]
@morallo ,

Yes, there is such an option in the main repo. 
At the same time, it makes sense to move it into atc-react to make the project fully independent.

So I just did. 

I will update README with a guideline soon, but you can already use it by updating the configuration file and investigation `main.py` keys.
